version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/functions/log-event/"
      - "/functions/process-events/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directories:
      - "/ui/extensions/user-preferences/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
