version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/functions/log-event/"
      - "/functions/process-events/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
