version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/functions/log-event/"
      - "/functions/process-events/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: npm
    directory: "/ui/extensions/user-preferences/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
