name: Test log-event function
provision_on_install: true
trigger:
    next:
        - log_event_handler_c92702d3
actions:
    log_event_handler_c92702d3:
        id: functions.log-event.log_event_handler
        properties:
            event_data:
                quote: Tis' merely a flesh wound.
