name: Test process-events function
provision_on_install: true
trigger:
    next:
        - process_events_handler_ffcdec03
actions:
    process_events_handler_ffcdec03:
        id: functions.process-events.process_events_handler
        properties:
            workflow_id: ${Trigger.TriggerSource.Workflow.DefinitionID}
