name: Test user_preferences collection
description: Workflow for user_preferences collection to verify it works
provision_on_install: true
trigger:
    next:
        - list_objects_in_user_preferences_b6adad5b
    name: On demand
    parameters:
        properties:
            email:
                type: string
                title: Email
                default: matt.raible@crowdstrike.com
                format: email
            last-updated:
                type: string
                title: Last Updated
                default: "50"
            object-key:
                type: string
                title: Object Key
                default: "42"
        type: object
    type: On demand
actions:
    add_object_to_user_preferences_f9ef7ba8:
        next:
            - search_objects_in_user_preferences_530cba17
        properties:
            custom_storage_object_key: ${object-key}
            dashboardLayout: standard
            lastUpdated: ${last-updated}
            notificationsEnabled: true
            theme: light
            userId: ${email}
    list_objects_in_user_preferences_b6adad5b:
        next:
            - add_object_to_user_preferences_f9ef7ba8
        properties: {}
    search_objects_in_user_preferences_530cba17:
        properties:
            custom_storage_search_filter: userId:'matt.raible@crowdstrike.com'
