name: Test user_preferences collection
description: Workflow for user_preferences collection to verify it works
provision_on_install: true
trigger:
    next:
        - list_objects_in_user_preferences_de4b804d
actions:
    list_objects_in_user_preferences_de4b804d:
        id: collections.user_preferences.list
        properties: {}
