name: Test process_events_handler function
description: Workflow to invoke process_events_handler function and verify it works
provision_on_install: true
trigger:
    next:
        - process_events_handler_34e22c4e
    name: On demand
    parameters:
        properties:
            workflow_id:
                type: string
                title: Workflow ID
        type: object
actions:
    process_events_handler_34e22c4e:
        id: functions.process-events.process_events_handler
        properties:
            workflow_id: ${workflow_id}
